# Generated by Django 5.2.8 on 2025-11-12 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShootingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_deducted', models.IntegerField(default=1)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shooting Attendance',
                'verbose_name_plural': 'Shooting Attendances',
                'db_table': 'shooting_attendance',
            },
        ),
        migrations.CreateModel(
            name='ShootingNight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(choices=[('hall', 'Hall'), ('meadow', 'Meadow'), ('woods', 'Woods')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(related_name='attended_shooting_nights', through='shooting.ShootingAttendance', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shooting_nights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shooting Night',
                'verbose_name_plural': 'Shooting Nights',
                'db_table': 'shooting_shootingnight',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='shootingattendance',
            name='shooting_night',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='shooting.shootingnight'),
        ),
        migrations.AlterUniqueTogether(
            name='shootingattendance',
            unique_together={('shooting_night', 'user')},
        ),
    ]
