"""Refactor shoots and credits system

Revision ID: 316fc5a90bd1
Revises: 4f21359797f4
Create Date: 2025-11-17 22:25:09.551299

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "316fc5a90bd1"
down_revision = "4f21359797f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("credits", schema=None) as batch_op:
        batch_op.drop_column("expiry_date")
        batch_op.drop_column("purchase_date")
        batch_op.drop_column("used")

    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.add_column(sa.Column("credits", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "status",
            existing_type=mysql.ENUM("active", "expired", "cancelled"),
            type_=sa.String(length=20),
            existing_nullable=True,
        )
        batch_op.drop_column("nights_used")

    with op.batch_alter_table("shoots", schema=None) as batch_op:
        batch_op.alter_column(
            "date",
            existing_type=mysql.DATETIME(),
            type_=sa.Date(),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "location",
            existing_type=mysql.VARCHAR(length=255),
            type_=sa.Enum("HALL", "MEADOW", "WOODS", name="shootlocation"),
            existing_nullable=False,
        )
        batch_op.drop_column("capacity")

    with op.batch_alter_table("user_shoots", schema=None) as batch_op:
        batch_op.add_column(sa.Column("attended_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_shoots", schema=None) as batch_op:
        batch_op.drop_column("attended_at")

    with op.batch_alter_table("shoots", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("capacity", mysql.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.alter_column(
            "location",
            existing_type=sa.Enum("HALL", "MEADOW", "WOODS", name="shootlocation"),
            type_=mysql.VARCHAR(length=255),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "date",
            existing_type=sa.Date(),
            type_=mysql.DATETIME(),
            existing_nullable=False,
        )

    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "nights_used", mysql.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.String(length=20),
            type_=mysql.ENUM("active", "expired", "cancelled"),
            existing_nullable=True,
        )
        batch_op.drop_column("credits")

    with op.batch_alter_table("credits", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("used", mysql.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(sa.Column("purchase_date", mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column("expiry_date", mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
