"""Tidy up user_shoots table

Revision ID: 4f21359797f4
Revises: 001
Create Date: 2025-11-17 22:19:11.290050

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "4f21359797f4"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=mysql.VARCHAR(length=20),
            type_=sa.Enum("active", "expired", "cancelled"),
            existing_nullable=True,
        )

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.alter_column(
            "payment_type",
            existing_type=mysql.VARCHAR(length=20),
            type_=sa.Enum("membership", "credits"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "status",
            existing_type=mysql.VARCHAR(length=20),
            type_=sa.Enum("pending", "completed", "failed", "cancelled"),
            existing_nullable=True,
        )

    with op.batch_alter_table("user_shoots", schema=None) as batch_op:
        batch_op.drop_column("attended_at")
        batch_op.drop_column("credits_used")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_shoots", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "credits_used", mysql.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(sa.Column("attended_at", mysql.DATETIME(), nullable=True))

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum("pending", "completed", "failed", "cancelled"),
            type_=mysql.VARCHAR(length=20),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "payment_type",
            existing_type=sa.Enum("membership", "credits"),
            type_=mysql.VARCHAR(length=20),
            existing_nullable=False,
        )

    with op.batch_alter_table("memberships", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum("active", "expired", "cancelled"),
            type_=mysql.VARCHAR(length=20),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
