"""remove date of birth from user model

Revision ID: 76cf717955c8
Revises: 008
Create Date: 2025-12-15 23:12:19.818458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cf717955c8'
down_revision = '008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_external_transaction_id'))
        batch_op.create_index(batch_op.f('ix_payments_external_transaction_id'), ['external_transaction_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), nullable=False))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_external_transaction_id'))
        batch_op.create_index(batch_op.f('ix_payments_external_transaction_id'), ['external_transaction_id'], unique=False)

    # ### end Alembic commands ###
